[tool.poetry]
name = "fable-saga"
version = "0.2.0"
description = "AI agents that turn skills into actions."
authors = ["Frank Carey <fcarey@gmail.com>"]
readme = "README.md"
packages = [{include = "fable_agents"}]

[tool.poetry.dependencies]
python = "^3.10"
cattrs = "^23.1.2"
langchain = {extras = ["llms"], version = "^0.0.293"}


[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
# The only dependencies that should be added are
# dependencies used for running tests (e.g., pytest, freezegun, response).
pytest = "^7.3.0"
pytest-asyncio = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
