[tool.poetry]
name = "fable-generative-agents"
version = "0.1.0"
description = ""
authors = ["Frank Carey <fcarey@gmail.com>"]
readme = "README.md"
packages = [{include = "fable_agents"}]

[tool.poetry.dependencies]
python = "^3.10"
python-socketio = "^5.9.0"
cattrs = "^23.1.2"
aiohttp = "^3.8.5"
langchain = {extras = ["llms"], version = "^0.0.293"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
